borderpx = 3
snap = 32
showbar = true
topbar = true
mfact = 0.5
nmaster = 1
resize_hints = false
lock_fullscreen = true

fonts = ["monospace:size=10"]
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]