let borderpx = 3;
let snap = 32;
let showbar = true;
let topbar = true;
let mfact = 0.5;
let nmaster = 1;
let resize_hints = false;
let lock_fullscreen = true;

let fonts = ["monospace:size=10"];
let tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"];